routes/web.php
<?php
/*------------------------For User---------------------------*/
Route::get('/',[ 'as'=>'index', 'uses'=>'FrontController@index']);
Route::get('/profile','FrontController@showprofile')->name('profile');
Route::get('/userPost','FrontController@showuserPost')->name('userPost');
Route::get('/singlePost/{id}','FrontController@show')->name('singlePost');
Route::get('/categorywisepost/{id}','FrontController@showPostCategorywise')->name('categorywisepost');
Route:: get('/search','FrontController@search');
Auth::routes();
/*------------------------For Admin-------------------------*/
Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function () {
    Route::resource('post','PostController');
//    Route:: get('/search','PostController@search');
    Route::post('post/changeStatus',['as'=>'post.changeStatus', 'uses'=>'PostController@changeStatus']);
    Route::get('post/allPostForAdmin',['as'=>'post.allPostForAdmin', 'uses'=>'PostController@allPostForAdmin']);
    Route::resource('category','CategoryController');
    Route::resource('gallery','GalleryController');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    //
    protected $table = 'posts';
    protected $primaryKey = 'post_id';
    protected $fillable = ['post_title','category_id','user_id','post_description','post_slug', 'approved_status'];

    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id', 'category_id');
    }

    public function gallery() {
        return $this->belongsToMany('App\Gallery'); //  or whatever your namespace is
    }
    public function author()
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }

}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Gallery;
use App\Post;
use http\Env\Response;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class PostController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['posts'] = Post::all();
        $data['categories'] = Category::all();

//        $posts = Post::with('category')->get();
//        return view('admin.post.index',compact('posts'));


        return view('user.post.userPost',$data);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function create()
    {
        $categories = Category::get();
        return view('user.post.create',compact('categories'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
//        $this->validate($request,[
//            'post_title' => 'required',
//            'category_id' => 'required',
//            'post_description' =>'required'
//        ]);
//        $inputs = [];
       $postRequest = $request->only('user_id','post_title','category_id','post_description');
       $postRequest['post_slug'] = Str::slug($request->post_title,'-');
       $postRequest['approved_status'] =  $request->has('approved_status')? true:false;
        // $postRequest->approved_status;

       $post = Post::create($postRequest);




        // for multiple image upload


        $postGallery = [];
        $images = $request->file('path');

        $postGallery['post_id'] = $post->post_id;

        foreach($images as $image) {

//            $name= rand(11111, 99999) . '.' . $image['path']->getClientOriginalExtension();
//            $image['path']->move(public_path('/images/'), $name);
//            $postGallery['path'] = $name;
//            $postGallery['type'] = 'image';
//            Gallery::create($postGallery);

            $destinationPath = public_path('/images/'); // upload path
            $profileImage = date('YmdHis') . "." . $image->getClientOriginalExtension();
            $image->move($destinationPath, $profileImage);


            $postGallery['path'] = $profileImage;
            $postGallery['type'] = 'image';
            Gallery::create($postGallery);

        }
////        for video upload
//        $videos = $request->file('path');
//
//        foreach($videos as $video) {
//            $destinationPath = public_path('/videos/');
//
//            $request->file('path')->move(public_path('videos'), $request->file('path')->getClientOriginalName());
//            $video->path = public_path('videos') . '/' . $request->file('path')->getClientOriginalName();
//            $postGallery['path'] = $video;
//            $postGallery['type'] = 'video';
//            Gallery::create($postGallery);
//        }
//        for upload one picture only
//            $postGallery = $request->only('path', 'post_id');
//            $postGallery['post_id'] = $post->post_id;
//
//            $name = rand(11111, 99999) . '.' . $request->path->getClientOriginalExtension();
//            $postGallery['path']->move(public_path('/images/'), $name);
//            $postGallery['path'] = $name;
//            $postGallery['type'] = 'image';
//
//
//
//        Gallery::create($postGallery);



        return redirect()->route('post.index')->with('success','Post Submitted');

    }


    public function show($id)
    {
        //
    }


    public function edit($id)
    {
        $data['post'] = Post::query()->where('post_id','=',$id)->first();
        $data['posts'] = Post::get();
        $data['categories'] = Category::get();
        return view('admin.post.edit', $data);
    }


       public function update(Request $request, $id)
    {

        $this->validate($request,[
            'post_title' => 'required',
            'category_id' => 'required',
            'post_description' =>'required'
        ]);
        $post = Post::where('post_id', $id)->first();
        $inputs = [];
        $inputs = $request->all();
        $inputs['post_slug'] = Str::slug($request->post_title,'-');
//        $inputs['user_id'] = Auth::user()->id;

        $post->update($inputs);
        return redirect()->route('post.index')->with('success','Post updated');
    }


    public function destroy($id)
    {
        $post = Post::where('post_id',$id);
        $post->delete();
        return redirect()->route('post.index')->with('success','Post Deleted');

    }
     public function changeStatus(Request $request)
    {
        $post = Post::where('post_id', $request->post_id)->first();

        if($post->approved_status == 0)
            $inputs['approved_status'] = 1;
        else
            $inputs['approved_status'] = 0;

        $post->update($inputs);
        //return response()->json(['success'=>'Approved status change successfully.']);
    }
    public function allPostForAdmin()
    {
        $data['posts'] = Post::all();
        $data['categories'] = Category::all();

        return view('admin.post.index',$data);
    }
}

resources/views/admin/post/create.blade.php
@extends('admin.layouts.app')
@section('content')
    <div class="container-fluid">
        <!-- Breadcrumb-->
        <div class="row pt-2 pb-2">
            <div class="col-sm-9">
                <h4 class="page-title">Add Post</h4>
            </div>

        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <form method="post" action="{{route('post.store')}}" enctype="multipart/form-data">
                            @csrf
                            <div class="form-group row">
                                <label for="basic-input" class="col-sm-3 col-form-label">Post Title</label>
                                <div class="col-sm-9">
                                    <input type="text" id="basic-input"  name="post_title" class="form-control">
                                </div>
                            </div>
                            <input type="hidden" name="user_id" value="{{ Auth::user()->id }}">
                            <div class="form-group row">
                                <label for="basic-select" class="col-sm-3 col-form-label">Select Post Category</label>
                                <div class="col-sm-9">
                                    <select  class="form-control" name="category_id">
                                        @foreach($categories as $row)
                                            <option value="{{$row['category_id']}}">{{$row['category_name']}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="basic-textarea" class="col-sm-3 col-form-label">Description</label>
                                <div class="col-sm-9">
                                    <textarea rows="10" class="form-control" name="post_description" id="basic-textarea"></textarea>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="basic-textarea" class="col-sm-3 col-form-label">Post Image</label>
                                <div class="col-sm-9">
                                <input type="file" name="path[]" multiple>
                                </div>
                            </div>


                            <div class="form-group row">
                                <div class="col-offset-md-9 col-sm-3">
                                    <button type="submit" class="btn btn-primary">Create</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div><!--End Row-->
    </div>
    @endsection

resources/views/admin/post/edit.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="container-fluid">
        <!-- Breadcrumb-->
        <div class="row pt-2 pb-2">
            <div class="col-sm-9">
                <h4 class="page-title">Edit Post</h4>
            </div>

        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <form method="POST" action="{{route('post.update', $post->post_id)}}">
                            @csrf
{{--                            @method('PUT')--}}
                            <input type="hidden" name="_method" value="PATCH" />
                            <div class="form-group row">
                                <label for="basic-input" class="col-sm-3 col-form-label">Post Title</label>
                                <div class="col-sm-9">
                                    <input type="text" id="basic-input"  name="post_title" value="{{$post->post_title}}" class="form-control">
                                </div>
                            </div>
{{--                            <input type="hidden" name="user_id" value="{{ Auth::user()->id }}">--}}
                            <div class="form-group row">
                                <label for="basic-select" class="col-sm-3 col-form-label">Select Post Category</label>
                                <div class="col-sm-9">
                                    <select  class="form-control" name="category_id">
                                        @foreach($categories as $row)
                                            <option value="{{$row->category_id}}" @if($post->category_id==$row->category_id) selected @endif>{{$row->category_name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="basic-textarea" class="col-sm-3 col-form-label">Description</label>
                                <div class="col-sm-9">
                                    <textarea rows="10" class="form-control" name="post_description"  id="basic-textarea">{{$post->post_description}}</textarea>
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-offset-md-9 col-sm-3">
                                    <button type="submit" class="btn btn-primary">Edit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div><!--End Row-->
    </div>
@endsection

resources/views/admin/post/index.blade.php
@extends('admin.layouts.app')
<!--   <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" ></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css"  />
    <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script> -->
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                @if($message = Session::get('success'))
                    <div class="alert alert-success">
                        <p>{{$message}}</p>
                    </div>
                @endif
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header"><i class="fa fa-table"></i> All Post</div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table id="example" class="table table-bordered">
                                <thead>
                                <tr>
                                    <th>Sl No.</th>
                                    <th>Post Title</th>
                                    {{--<th>Parent Id</th>--}}
                                    <th>Post Category</th>
                                    <th>Post Description</th>
                                    <th>Approved Status</th>
                                    {{--<th>Slug</th>--}}
                                    <th>Edit</th>
                                    <th>Delete</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($posts as $row)

                                    <tr>
                                        <td>{{$loop->iteration}}</td>
                                        <td>{{$row->post_title}}</td>
                                        <td>{{$row->category->category_name}}</td>
                                        <td>{{$row->post_description}}</td>
                                        <td>

                   <!-- <input type="checkbox" name="approved_status" value="{{$row->id}}">  -->
 <!--  {{Form::checkbox('approved_status',1, $row->approved_status,array('id' => 'some-id'))}}  -->

                                           <!--  <input onclick="id()" id="toggle-class"  class="toggle-class"  type="checkbox" data-onstyle="success" data-offstyle="danger"data-toggle="toggle"> -->

                                          <input value="{{$row->approved_status}}" data-id="{{$row->post_id}}" type="checkbox" class="status_change" name="approved_status" {{ $row->approved_status==1 ? 'checked' : '' }} />

                                        </td>

                                        <td><a href="{{route('post.edit',$row->post_id)}}" class="btn btn-info">Edit</a></td>
                                        <td>
                                            <form method="POST" action="{{route('post.destroy',$row->post_id)}}">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-danger">Delete</button>
                                            </form>
                                        </td>
                                    </tr>

                                @endforeach

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

 @push("scripts")
<script>

    $(".status_change").click(function(){

    var post_id = $(this).data('id');
     // alert(post_id);
     $.ajax({
      type: "POST",

       dataType: "json",
      url: "{{route('post.changeStatus')}}",
      data: { 'post_id': post_id,'_token': "{{ csrf_token() }}"},
     success: function(data){
        alert(data.success);
       }
  });
    });

</script>

@endpush