routes/web.php
<?php
/*------------------------For User---------------------------*/
Route::get('/',[ 'as'=>'index', 'uses'=>'FrontController@index']);
Route::get('/profile','FrontController@showprofile')->name('profile');
Route::get('/userPost','FrontController@showuserPost')->name('userPost');
Route::get('/singlePost/{id}','FrontController@show')->name('singlePost');
Route::get('/categorywisepost/{id}','FrontController@showPostCategorywise')->name('categorywisepost');
Route:: get('/search','FrontController@search');
Auth::routes();
/*------------------------For Admin-------------------------*/
Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function () {
    Route::resource('post','PostController');
//    Route:: get('/search','PostController@search');
    Route::post('post/changeStatus',['as'=>'post.changeStatus', 'uses'=>'PostController@changeStatus']);
    Route::get('post/allPostForAdmin',['as'=>'post.allPostForAdmin', 'uses'=>'PostController@allPostForAdmin']);
    Route::resource('category','CategoryController');
    Route::resource('gallery','GalleryController');
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'user_type'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];



    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

resources/views/user/includes/footer.blade.php
<footer class="footer-area section-gap">
    <div class="container box_1170">
        <div class="row">
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6 class="footer_title">About Us</h6>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore dolore
                        magna aliqua.</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6 class="footer_title">Newsletter</h6>
                    <p>Stay updated with our latest trends</p>
                    <div id="mc_embed_signup">
                        <form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                              method="get" class="subscribe_form relative">
                            <div class="input-group d-flex flex-row">
                                <input name="EMAIL" placeholder="Email Address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Email Address '"
                                       required="" type="email">
                                <button class="btn sub-btn"><span class="lnr lnr-arrow-right"></span></button>
                            </div>
                            <div class="mt-10 info"></div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-6">
                <div class="single-footer-widget instafeed">
                    <h6 class="footer_title">Instagram Feed</h6>
                    <ul class="list instafeed d-flex flex-wrap">
                        <li><img src="img/i1.jpg" alt=""></li>
                        <li><img src="img/i2.jpg" alt=""></li>
                        <li><img src="img/i3.jpg" alt=""></li>
                        <li><img src="img/i4.jpg" alt=""></li>
                        <li><img src="img/i5.jpg" alt=""></li>
                        <li><img src="img/i6.jpg" alt=""></li>
                        <li><img src="img/i7.jpg" alt=""></li>
                        <li><img src="img/i8.jpg" alt=""></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-md-6 col-sm-6">
                <div class="single-footer-widget f_social_wd">
                    <h6 class="footer_title">Follow Us</h6>
                    <p>Let us be social</p>
                    <div class="f_social">
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-dribbble"></i></a>
                        <a href="#"><i class="fa fa-behance"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row footer-bottom d-flex justify-content-between align-items-center">
            <p class="col-lg-12 footer-text text-center"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
        </div>
    </div>
</footer>

resources/views/user/includes/header.blade.php
<header id="header">
    <div class="container box_1170 main-menu">
        <div class="row align-items-center justify-content-center d-flex">
            <nav id="nav-menu-container">
                <ul class="nav-menu">
                    @include('user.includes.navbar')
                </ul>
            </nav>
        </div>
    </div>
    @include('user.includes.searchbox')
</header>

resources/views/user/includes/logedinnavbar.blade.php
  <li class="menu-active"><a href="">Home</a></li>

   @foreach($categories as $key => $row )
       @php
                   //$child = app::make("FrontController")->ischild($row->category_id);
//                  $child =App\Http\Controllers\FrontController::ischild($row->category_id);

       $count = isset($row['subcategory']) ? count($row['subcategory']) : 0 ;
@endphp

              <li> <a href="{{$count>0 ? 'menu-has-children': ''}}">
                    {{$row['category_name']}}</a>
                    @if($count>0)
                         <ul>
                             @if(isset($row['subcategory']))
                                @foreach( $row['subcategory'] as $value)
                                    <li>
                                      <a href="elements.html">{{ $value['category_name'] }}</a>
                                    </li>
                                  @endforeach
                             @endif
                         </ul>
                    @endif
               </li>
     @endforeach
                    <li><a href="contact.html">Contact</a></li>

resources/views/user/includes/navbar.blade.php
<li class="menu-active"><a href="index.html">Home</a></li>
@foreach($categories as $key => $row )
    @php
        //$child = app::make("FrontController")->ischild($row->category_id);
//                  $child =App\Http\Controllers\FrontController::ischild($row->category_id);

$count = isset($row['subcategory']) ? count($row['subcategory']) : 0 ;
    @endphp
    <li> <a  class="{{$count>0 ? 'menu-has-children': ''}}" href=" {{route('categorywisepost',$row['category_id'])}}">
            {{$row['category_name']}}</a>
        @if($count>0)
            <ul>
                @if(isset($row['subcategory']))
                    @foreach( $row['subcategory'] as $value)
                        <li>
                            <a href="{{route('categorywisepost',$value['category_id'])}}">{{ $value['category_name'] }}</a>
                        </li>
                    @endforeach
                @endif
            </ul>
        @endif
    </li>
@endforeach

                    <li><a href="contact.html">Contact</a></li>
@if(Auth::user())
                    <li><a>Profile Setting</a>
                    <ul>
                    <li><a href="{{ route('profile') }}">Profile</a> </li>

                            <li><a href="{{ route('logout') }}"
                                    onclick="event.preventDefault();
                                   document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}</a>
                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </li>
                        </ul>
                    </li>
@endif

@if(!Auth::user())
                    <li><a href="{{ route('login') }}">Login</a></li>
                        @if (Route::has('register'))
                    <li><a href="{{ route('register') }}">Register</a></li>
                        @endif
    @endif

resources/views/user/includes/profileNavbar.blade.php
<li class="menu-active"><a href="{{route('userPost',$id)}}">ALL Post</a></li>

    <li> <a href="{{route('post.create')}}">Create Post</a></li>

resources/views/user/includes/searchbox.blade.php
<div class="search_input" id="search_input_box">
    <div class="container box_1170">
        <form class="d-flex justify-content-between" action="/search" method="get">
            @csrf
            <input type="search"  name="search" class="form-control" id="search_input" placeholder="Search Here">
            <button type="submit" class="btn"></button>
            <span class="lnr lnr-cross" id="close_search" title="Close Search"></span>
        </form>
    </div>
</div>